apiVersion: v1
kind: PersistentVolume
metadata:
  name: quality-gate-disk
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/quality-gate-disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kube-tests-node02

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: image-checker
  labels:
    name: image-checker
spec:
  serviceName: "image-checker"
  replicas: 1
  selector:
    matchLabels:
      app: image-checker
  template:
    metadata:
      labels:
        app: image-checker
    spec:
      containers:
        - name: image-checker
          image: sabsabbas/image-checker
          volumeMounts:
            - name: quality-gate-disk
              mountPath: /opt/sources
          securityContext:
            privileged: true

  volumeClaimTemplates:
    - metadata:
        name: quality-gate-disk
      spec:
        storageClassName: manual
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

